### PR TITLE
Proposal for Bayeux with CometD

### PR DESCRIPTION
**Pull request by kmyrhaug**
The plugin should be tested, perhaps in an integration test. Haven't looked in to how other plugins are tested yet.

### CODE REVIEW

**Comment by computerlove** [comment]
Er denne relevant lengre?

**Comment by kmyrhaug** [comment]
Nei, ikke relevant lengere.

**Comment by eirbjo** [comment]
Dylai'r holl sylwadau fod yn Saesneg :-)

**Comment by kmyrhaug** [comment]
All right. The pull request is not relevant anymore.

**Pull request closed without merging**
